### ISSUE TITLE
EPSG:4326 always as default CRS (enhancement)

### ISSUE THREAD

**Issue by juhele** [ctu-geoforall-lab-sandbox/qgis-map-coords-plugin#10]
Hi,
I would prefer to have EPSG:4326 always set as default. It is required by our other apps and now I always have to switch the CRS.

thanks

**Comment by landam** [comment]
@kalator @pikorcik ping

**Comment by landam** [comment]
@juhele @kalator Can we close the issue?

**Comment by juhele** [comment]
I think this issue was successfully solved and can be closed. thanks :-)
