### ISSUE TITLE
additional text parameters in text file

### ISSUE THREAD

**Issue by juhele** [ctu-geoforall-lab-sandbox/qgis-map-coords-plugin#11]
Current file structure of the text file is like:

`Map Corners Coordinates
SRS: EPSG:4326
NW (X): 13.9959085873
NW (Y): 49.2085345769
NE (X): 14.3951588431
NE (Y): 49.2085345769
SE (X): 14.3951588431
SE (Y): 49.003536038
SW (X): 13.9959085873
SW (Y): 49.003536038`

Would it be possible to:

1)  add text description to the corners like:

`NW (upper left) (X): 13.9959085873
NW (upper left) (Y): 49.2085345769`

for better a quicker orientation?

2) somehow help to identify the source project?
Set output file name by default same as project name or at least add project name to the text file?

thanks

Jan

**Comment by landam** [comment]
@juhele @kalator Is there anything missing or we can close the issue?

**Comment by juhele** [comment]
I think this issue was successfully solved and can be closed. thanks :-)
